blank_issues_enabled: false
contact_links:
  - name: Ryubing Troubleshooting/Support 
    url: https://discord.gg/c6sDayDFkt
    about: For support and technical issues, please come to our Discord server. We do not accept support requests on GitHub.
